### ISSUE TITLE
SourceAnalysis.from_file: Allow passing open file handle

### ISSUE THREAD

**Issue by Natureshadow** [roskakori/pygount#100]
In addition to only a path, it would be helpful if `SourceAnalysis.from_file` could be passed an open file handle.

That would help for analyzing code from files not available in the local filesystem directly, like from the object database of a Git repository. Specifically, I am writing a statistical analytics software for full Git repositories, and am reading data directly from Git objects instead of a working tree. Gitpython gives me a filename and a file-like object to read from.

**Comment by roskakori** [comment]
Sounds like a good idea.

Can you provide a small, self-contained code example how you would read a (hard coded) example file from e.g. the pygount repository using `gitpython`?

**Comment by Natureshadow** [comment]
=Sure, here you go. To analyze the file `pygoutn/analysis.py` from the second-to-last commit:

```python
from tempfile import TemporaryDirectory

import git
from pygount.analysis import SourceAnalysis


with TemporaryDirectory() as d:
    repo = git.Repo.clone_from("https://github.com/roskakori/pygount")
    file = repo.head.commit.parents[0].tree / "pygount" / "analysis.py"
    # Now, file.path is the relative path and name of the file, and
    #  file.data_stream is an open file-like object to read() from
    SourceAnalysis.from_file(file.path, fh=file.data_stream)
```

**Comment by Natureshadow** [comment]
The use-case is supported by mr PY #101 . The GitPython example above does not work though, because the GitPython developers have a different understanding of a file-like object than the rest of the work. But I can work around that in my project with the API in #101.

**Comment by Natureshadow** [comment]
Looking at the milestone in this issue: The new version should be 1.6.0, as this introduces a new feature. (cf. https://semver.org/)

**Comment by roskakori** [comment]
> Looking at the milestone in this issue: The new version should be 1.6.0, as this introduces a new feature.
True, changed it.

**Comment by roskakori** [comment]
@Natureshadow Thanks for the PR, finally got a look at it. For the most part it looks fine, left some questions as review comments.
