### ISSUE TITLE
Support for multiple output format

### ISSUE THREAD

**Issue by gsemet** [roskakori/pygount#142]
Hello

Can you generate more than 1 output format at once ? I would like to generate the json and the xml, and print in stdout the summary for instance.

Thanks.

**Comment by roskakori** [comment]
You can use only 1 output format at the same time.

If you need more than one, you can:
1. Run pygount multiple times with a different `--format` parameter.
2. Write a small Python script that uses the API to collect the statistics once and then write them multiple times.
