### ISSUE TITLE
Is there a way to pass the content of a file rather than the path?

### ISSUE THREAD

**Issue by erikbern** [roskakori/pygount#15]
I'm interested in integrating something like pygount into https://github.com/erikbern/git-of-theseus. I'm already using git blame under the hood for line-by-line statistics, but a general "file classifier" would be really helpful to default to.

Is there a way I can pass the content of a file and classify it (basically whether I should ignore it or not)?

**Comment by roskakori** [comment]
What exactly are you looking for? A Python routine or a command line tool.

In the current source code, `analysis.guess_lexer()` should come close to it but there are a couple of other functions that help to identify binary, empty, and plain text files. Nevertheless it should be simple to stitch something together from it.

**Comment by erikbern** [comment]
> What exactly are you looking for - a Python routine or a command line tool?

A Python routine that I can pass the content of a file to

Ended up using something simple based on pygments – just using the file extensions of their lexers for now.

> 
> In the current source code, analysis.guess_lexer() should come close to it but there are a couple of other functions that help to identify binary, empty, and plain text files. Nevertheless it should be simple to stitch something together from it.

Ok, cool, will take a look. Thanks!
