### ISSUE TITLE
Nice work. It's missing the sum of lines

### ISSUE THREAD

**Issue by victordomingos** [roskakori/pygount#16]
I just discovered pygount and was happy to find a utility like this written in Python. I have been using clock (in perl). 

One feature I guess is still missing is the presentation of the sum of lines for the entire file set while printing the results to stdout in the default format. We run in in a folder and in the end we still don't know how many lines of code the project has... :)

**Comment by roskakori** [comment]
I mostly use pygount in combination with Jenkins, where the sum of lines is computed automatically.

With the option `--format=cloc-xml` the XML contains the total count, for example:
```xml
<total blank="221" code="1008" comment="185" />
```

If you just need to know the sum, you can pipe the result of pygount into `awk`, for example:
```sh
pygount some_project | awk '{s+=$1} END {print s}'
```

By default, pygount uses the same format as `sloccount --details --wide`, which does not include a total sum either.

Do these options solve your issue? It would certainly possible to add a command line option like `--total` to only show the sum total of lines or `--summary` to show a break down similar to sloccount's default output but I think these days CI systems like Jenkins are the way to go which already offer an extensive visual break down including historic data.

**Comment by victordomingos** [comment]
I will take a look. I wanted just a small utility that would allow to get a quick answer without having to write a long command or use a more complex system. For me the --total option, or something similar, would be the best solution.

**Comment by PetrovskYYY** [comment]
Added this feature in [this pull request](https://github.com/roskakori/pygount/pull/18)

**Comment by roskakori** [comment]
I've merged this in a separate branch for now but it will need some cleanup.

The proposed `--summary` option somewhat clashes with `--format`. For instance, it doesn't make much sense to combine `--summary` and `--format=cloc`. Also the current implementation squeezes quite some dummy data into the existing `SourceAnalysis` class which seems rather ugly.

Currently I'm tending towards a new output format `--format=summary` that would collect the data during writing and also add a sum total at the end.

**Comment by roskakori** [comment]
Pygout 1.1.0 is released, use `--format=summary` to get output like this:
```
    Language      Code    %     Comment    %   
----------------  ----  ------  -------  ------
Python            1730   83.94      250   78.12
reStructuredText   271   13.15        0    0.00
Ant                 38    1.84        1    0.31
INI                 10    0.49        1    0.31
Bash                 8    0.39        2    0.62
TOML                 4    0.19        0    0.00
Text                 0    0.00       66   20.62
----------------  ----  ------  -------  ------
Sum total         2061              320
```
