### ISSUE TITLE
API use model - separate comments/documentation

### ISSUE THREAD

**Issue by svenka3** [roskakori/pygount#24]
Hello,
  Happy to see this utility, I am trying to use the API based analysis inside larger Python code. 

In the following example:

SourceAnalysis(path='pygount/analysis.py', language='Python', group='pygount', code=302, documentation=66, empty=62, string=23, state='analyzed', state_info=None)

Is there a way to extract the pure code (i.e. code without documentation/blanks etc.) say to a file or another string?

Idea is to look for some keywords in a source code, but exclude comments.

Thanks
Srini

**Comment by roskakori** [comment]
I think the easiest solution for that would be to use the pygments lexer directly and look at the token stream. The [pygments quickstart](https://pygments.org/docs/quickstart.html) explains how to obtain a lexer by name or guessing. After that just call `some_lexer.get_tokens()` and which returns a tuple `(type, text)` and filter for the `type` for keywords.
