### ISSUE TITLE
Remove deprecated code

### ISSUE THREAD

**Issue by roskakori** [roskakori/pygount#47]
Goals:

* [ ] Code marked with `@deprecated` is removed.
* [ ] Code marked with `# TODO #47: Remove deprecated code` is removed.

**Comment by snowkoli** [comment]
I'm working on this during EuroPython 2024 sprint.

**Comment by roskakori** [comment]
> I'm working on this during EuroPython 2024 sprint.

@snowkoli Hello and thanks for your interest in contributing. However, on site @m-gambone already is on this issue. Please come to the EuroPython discord > #sprints > pygount-Thread.
