### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by Kinzowa** [roskakori/pygount#50]
Hello, I installed this package with pip under Ubuntu but it's unable to find the command. Any idea?
`pip install pygount --user`

```
~/python/myproject$ pygount --format=summary myapp
pygount: command not found
```

**Comment by roskakori** [comment]
Which pip are you using resp. what is the output of:
```
which pip
```

**Comment by Kinzowa** [comment]
Hi Thomas I'm using `/home/user/.local/bin/pip`.

Yes it works with virtual env

**Comment by roskakori** [comment]
Hm, this looks good, no idea why it doesn't work then.

Which Ubuntu version are you using?

**Comment by roskakori** [comment]
Correction (I've never really user `--user` because I always build my own `venv`):

You need to add the `bin` folder of the user base folder to your `PATH`, e.g.:
```bash
export PATH="${PATH}:$(python3 -c 'import site; print(site.USER_BASE)')/bin"
```
See also: https://stackoverflow.com/questions/42988977/what-is-the-purpose-of-pip-install-user

**Comment by Kinzowa** [comment]
Thanks, it' doesn't work either :| possibly because there is no `pygount` file in my `~/.local/bin` I have no idea where the binary is. 

```
~/$ find ~ -name 'pygount'
/home/xx/venv/lib/python3.6/site-packages/pygount
/home/xx/venv/bin/pygount
```
These two files were installed in virtual env.

**Comment by roskakori** [comment]
Pip has an option `--log`, I just tried the following on my mac;
```bash
pip install pygount --user --log /tmp/pip.log
```
Among other things the `/tmp/pip.log` then includes the following lines:
```
2020-05-04T23:05:47,617   WARNING: The script pygount is installed in '/Users/xxx/.local/bin' which is not on PATH.
2020-05-04T23:05:47,617   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
```
Please try again with the `--log` option. Maybe it's similar on Ubuntu and you actually have to add `~/.local/bin`?

**Comment by roskakori** [comment]
@Kinzowa Closed because I assume my previous reply resolved your issue. If you still need help, reply to this and I reopen it.
