### ISSUE TITLE
A few special cases for c++

### ISSUE THREAD

**Issue by nkr0** [roskakori/pygount#51]
C/C++'s preprocessor directives gets counted as comments; things like `#include <iostream>` and all. This can be fixed by adding
```
if token_type in (pygments.token.Comment.Preproc, pygments.token.Comment.PreprocFile):
    line_marks.add("c")
```
[here](https://github.com/roskakori/pygount/blob/1b5f58241fcfefcb853fea2234130bb52828ef15/pygount/analysis.py#L654).

Furthermore, I see that lines with just braces and semicolons `};` are ignored. But I guess that's just your preference.

**Comment by roskakori** [comment]
Good find. Apparently pygments [C++ lexer](https://github.com/pygments/pygments/blob/master/pygments/lexers/c_cpp.py) classifies preprocessor statements as comments, but I agree that they should be counted as code.

About the not counting `{` etc: yes, this is a deliberate choice, it's explained in the documentation section on "[How pygount counts code](https://pygount.readthedocs.io/en/latest/background.html#how-pygount-counts-code)".

**Comment by roskakori** [comment]
@nkr0 Your suggestion has been incorporated into version 1.2.2, which is available form PyPI.

**Comment by nkr0** [comment]
Thanks. I compared pygount (with `white_characters` disabled) with `cloc` on a fairly large c++ project and both gave exactly the same number. :)
