### ISSUE TITLE
"pygount ." does nothing

### ISSUE THREAD

**Issue by denizdogan** [roskakori/pygount#56]
For some reason pygount . does nothing and just exits, but pygount `pwd` works.

**Comment by roskakori** [comment]
I suppose the default regex to ignore everything starting with "." is the culprit here. 🤔

**Comment by roskakori** [comment]
Confirmed:
```python
#: Default glob patterns for folders not to analyze.
DEFAULT_FOLDER_PATTERNS_TO_SKIP_TEXT = ", ".join(
    [".*", "_svn", "__pycache__"]  # Subversion hack for Windows  # Python byte code
)
```
The first entry should be `".?*"` instead of `".*"`. (And it's not a regex but a glob pattern. Same issue though.)

**Comment by roskakori** [comment]
Version 1.2.4 fixes this and is now available on PyPI.
