### ISSUE TITLE
add support for unknown files to use a known syntax

### ISSUE THREAD

**Issue by tijimathew** [roskakori/pygount#58]
I am new to open source and python in general. I would like to explore the options for add a feature like --user-syntax for unknown files. I particularly was trying to use it on .btq files which is mostly teradata command line file laced with sql statements. Can we look at adding this as an enhancement ?

**Comment by roskakori** [comment]
The best way would be to [write a lexer for pygments](https://pygments.org/docs/lexerdevelopment/), then pygount automatically recognizes and counts the file. If BTQ is similar enough to existing SQL dialects, you might just add the suffix "*.btq" to the existing generic SQL lexer.

**Comment by tijimathew** [comment]
Thank you for the detailed response. Both your suggestions are helpful in moving forward. BTEQ is a combination Teradata shell commands and SQL. In the interim, I was able to tinker with CLOC and get the BTEQ lines of code to be customized from the SQL syntax. Now, I can try the delegate option you suggested and the write the lexer for bteq if I can. I would consider my question answered.
