### ISSUE TITLE
Pygount issues with Cappuccino

### ISSUE THREAD

**Issue by ichbinsnicht** [roskakori/pygount#92]
Dear pygount team,

we have an issue to get the output for cappuccino through pygount. We contacted the owner of the pygount and he suggested that it is an issue with pygmentize. However, neither the pygmentize team (https://github.com/pygments/pygments/issues/2215) nor our team could replicate that issue with pygmentize.

We are hoping that you could help us with this issue.

Best,
Manuel

**Comment by roskakori** [comment]
I added a comment to the pygments issue: https://github.com/pygments/pygments/issues/2215#issuecomment-1229547550

**Comment by izahn** [comment]
Fixed now in pygments https://github.com/pygments/pygments/pull/2225#event-7394788858
