### ISSUE TITLE
Update dependency on chardet<5,>=4

### ISSUE THREAD

**Issue by colinet** [roskakori/pygount#93]
pygount 14.0 requires chardet<5,>=4 while latest chardet is 5.1.0.
Tested pygount 14.0 with chardet ==5.1.0 seems to run fine.

Any plan to update the dependancy on chardet version ?

**Comment by roskakori** [comment]
IIRC chardet 5 requires Python 3.7 while pygount 1.4.0 should still be able to run with Python 3.6.

As Python 3.6 is not maintained anymore, it should be fine to switch to chardet 5.

**Comment by roskakori** [comment]
@colinet This has been implemented with version 1.5.0 and published on PyPI.

**Comment by colinet** [comment]
I tested successfully version 1.5.0.
Thx a lot.
